### ISSUE TITLE
Корректная обработка запросов к несуществующим переменным

### ISSUE THREAD

**Issue by avtopro** [UncleGennady/test_abp#1]
Важно учесть, что ID переменной мы получаем из URL страницы — а это ненадёжный ресурс, который может быть изменён пользователем (случайно, или намеренно), поэтому доверять этим данным без перепроверки нельзя. Например, может быть запрошена страница несуществующей переменной https://test-abp.vercel.app/variables/999, на которой сейчас мы получаем необработанное исключение `Uncaught TypeError: Cannot read properties of undefined (reading 'Name')`.

То есть, в функции renderVariable не хватает проверки на наличие значения в переменной variable, до того как мы пытаемся это значение прочитать.

https://github.com/UncleGennady/test_abp/blob/53157079061433a038c79d59be1b69cb0b4f8720/src/pages/variable/index.jsx#L10-L26

**Comment by UncleGennady** [comment]
Исправлено  добавлением проверки и редиректа на главную:
https://github.com/UncleGennady/test_abp/blob/9b21ab0cb20b06f57bfaec88a032461960404ae4/src/pages/variable/index.jsx#L13-L37
